<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'PhabricatorPolicyRuleTaskSubscribers' => 'src/PhabricatorPolicyRuleTaskSubscribers.php',
    'SecurityPolicyEnforcerAction' => 'src/SecurityPolicyEnforcerAction.php',
    'SecurityPolicyEnforcerTestCase' => 'src/__tests__/SecurityPolicyTestCase.php',
    'SecurityPolicyEventListener' => 'src/SecurityPolicyListener.php',
    'WMFSecurityPolicy' => 'src/WMFSecurityPolicy.php',
  ),
  'function' => array(),
  'xmap' => array(
    'PhabricatorPolicyRuleTaskSubscribers' => 'PhabricatorPolicyRule',
    'SecurityPolicyEnforcerAction' => 'HeraldCustomAction',
    'SecurityPolicyEnforcerTestCase' => 'PhabricatorTestCase',
    'SecurityPolicyEventListener' => 'PhutilEventListener',
  ),
));
