<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'SecurityPolicyEnforcerAction' => 'policy/SecurityPolicyEnforcerAction.php',
    'WMFEscalateTaskController' => 'policy/WMFLockTaskController.php',
    'WMFEscalateTaskEventListener' => 'policy/WMFLockTaskEventListener.php',
    'WMFExtensionsApplication' => 'policy/WMFExtensionsApplication.php',
    'WMFSecurityPolicy' => 'policy/WMFSecurityPolicy.php',
    'WMFSubscribersPolicyRule' => 'policy/WMFSubscribersPolicyRule.php',
  ),
  'function' => array(),
  'xmap' => array(
    'SecurityPolicyEnforcerAction' => 'HeraldAction',
    'WMFEscalateTaskController' => 'PhabricatorController',
    'WMFEscalateTaskEventListener' => 'PhabricatorEventListener',
    'WMFExtensionsApplication' => 'PhabricatorApplication',
    'WMFSubscribersPolicyRule' => 'PhabricatorPolicyRule',
  ),
));
